import type { GeneratedResumeHistoryItem } from "@/lib/generated-resume-types"

export const mockGeneratedResumeHistory: GeneratedResumeHistoryItem[] = [
  {
    id: "resume_hist_001",
    sessionId: "sess_hist_001",
    kind: "chat",
    status: "completed",
    title: "Currículo gerado",
    description: "Versão legada preservada no histórico.",
    targetRole: null,
    targetJobSnippet: null,
    createdAt: "2026-04-24T13:10:00.000Z",
    completedAt: "2026-04-24T13:18:00.000Z",
    relativeCreatedAt: "há cerca de 2 horas",
    pdfAvailable: true,
    docxAvailable: false,
    downloadPdfUrl: "/api/file/sess_hist_001?download=pdf",
    downloadDocxUrl: null,
    viewerUrl: "/dashboard/resume/compare/sess_hist_001",
  },
  {
    id: "resume_hist_002",
    sessionId: "sess_hist_002",
    kind: "ats_enhancement",
    status: "completed",
    title: "Currículo ATS otimizado",
    description: "Melhoria geral para compatibilidade ATS, clareza e estrutura.",
    targetRole: null,
    targetJobSnippet: null,
    createdAt: "2026-04-23T15:30:00.000Z",
    completedAt: "2026-04-23T15:36:00.000Z",
    relativeCreatedAt: "há cerca de 1 dia",
    pdfAvailable: true,
    docxAvailable: false,
    downloadPdfUrl: "/api/file/sess_hist_002?download=pdf",
    downloadDocxUrl: null,
    viewerUrl: "/dashboard/resume/compare/sess_hist_002",
  },
  {
    id: "resume_hist_003",
    sessionId: "sess_hist_003",
    kind: "target_job",
    status: "completed",
    title: "Currículo para Data Analyst",
    description: "Adaptado para vaga: \"Senior Data Analyst com SQL e Power BI.\"",
    targetRole: "Data Analyst",
    targetJobSnippet: "Senior Data Analyst com SQL e Power BI.",
    createdAt: "2026-04-23T11:05:00.000Z",
    completedAt: "2026-04-23T11:10:00.000Z",
    relativeCreatedAt: "há cerca de 1 dia",
    pdfAvailable: true,
    docxAvailable: false,
    downloadPdfUrl: "/api/file/sess_hist_003?download=pdf&targetId=target_003",
    downloadDocxUrl: null,
    viewerUrl: "/dashboard/resume/compare/sess_hist_003",
  },
  {
    id: "resume_hist_004",
    sessionId: "sess_hist_004",
    kind: "ats_enhancement",
    status: "processing",
    title: "Currículo ATS otimizado",
    description: "Melhoria geral para compatibilidade ATS, clareza e estrutura.",
    targetRole: null,
    targetJobSnippet: null,
    createdAt: "2026-04-22T18:22:00.000Z",
    completedAt: null,
    relativeCreatedAt: "há cerca de 2 dias",
    pdfAvailable: false,
    docxAvailable: false,
    downloadPdfUrl: null,
    downloadDocxUrl: null,
    viewerUrl: "/dashboard/resume/compare/sess_hist_004",
  },
  {
    id: "resume_hist_005",
    sessionId: "sess_hist_005",
    kind: "target_job",
    status: "failed",
    title: "Currículo adaptado para vaga",
    description: "Versão adaptada com base na descrição da vaga informada.",
    targetRole: null,
    targetJobSnippet: "Cargo com foco em analytics engineering e dbt.",
    createdAt: "2026-04-21T10:45:00.000Z",
    completedAt: null,
    relativeCreatedAt: "há cerca de 3 dias",
    pdfAvailable: false,
    docxAvailable: false,
    downloadPdfUrl: null,
    downloadDocxUrl: null,
    viewerUrl: "/dashboard/resume/compare/sess_hist_005",
  },
  {
    id: "resume_hist_006",
    sessionId: "sess_hist_006",
    kind: "chat",
    status: "completed",
    title: "Currículo gerado",
    description: "Versão legada preservada no histórico.",
    targetRole: null,
    targetJobSnippet: null,
    createdAt: "2026-04-20T08:15:00.000Z",
    completedAt: "2026-04-20T08:21:00.000Z",
    relativeCreatedAt: "há cerca de 4 dias",
    pdfAvailable: true,
    docxAvailable: false,
    downloadPdfUrl: "/api/file/sess_hist_006?download=pdf",
    downloadDocxUrl: null,
    viewerUrl: "/dashboard/resume/compare/sess_hist_006",
  },
]
